### PR TITLE
Fixed #777 preserve newline character for narratives

### LINKED ISSUE #777: Preserve newline character for narratives
Many narratives entered by users are quite long. Unfortunately, paragraphs entered in the input get rendered as a single line in the output, making it more difficult to read. This is to request that newlines entered in the multi-line free-text fields be preserved in the output (results page and PDF).

E.g. of input:
image

And how it currently gets rendered, with newlines removed.
image

### PR DESCRIPTION
**Pull request by Ancentury**

### CODE REVIEW

**Comment by MrDeshaies** [comment]
Hi @Ancentury, browser.js is a local copy of an imported library. Can you please clarify how it was updated (where it was sourced from), or what changes were made? Thanks.

**Comment by Ancentury** [comment]
@MrDeshaies This is updated from their cdn https://cdn.jsdelivr.net/npm/html-to-pdfmake/browser.js, I suggest to include this in the package instead of linking from index.html.

**Comment by MrDeshaies** [comment]
In testing, only the translations show up correctly; the original input captured in the survey.js form does not.
[newlines_test_json.txt](https://github.com/canada-ca/aia-eia-js/files/7508591/newlines_test_json.txt) 

For example, if I do everything in English: complete the AIA in English (screens 1-13), then complete to view the results. The initial input does not keep new lines when viewing the English results or English PDF.

**Comment by Ancentury** [comment]
@MrDeshaies You're right. Thank you. Updated. :)

**Review by MrDeshaies — APPROVED** [review]

**Pull request merged**
