### PR TITLE
Fix Breaking CI/Build Issues - (Revert + Bump Dependencies)

### PR DESCRIPTION
**Pull request by ShadeWyrm**
@nschonni / @ptd-tbs / @MrDeshaies  - a series of pull request from bumping packages broke the AIA preventing it from deploying new versions.

CDS is looking to provide a demonstration of the AIA's capabilities, and would like to ensure it's in working order prior to the demo. :)

This PR fixes that, and bumps several of the packages that were trying to be fixed/bumped by Dependabot.

-> Closes #992 due to duplicate (and no longer working) effort.
-> Closes #850 (just has that change in it too)

Resolves the following dependabot asks:
-> Closes #1057 
-> Closes #951 
-> Closes #948

### CODE REVIEW

**Comment by nschonni** [comment]
There is a merge conflict with both the files

**Comment by ShadeWyrm** [comment]
> There is a merge conflict with both the files

Fixed, sorry @nschonni :)

**Review by nschonni — APPROVED** [review]
Rubber stamp approval, I didn't pull down and test this, but I know previously the updates I had tried and rolled back had broken stuff, and I guess this has happened again

**Comment by ShadeWyrm** [comment]
> Rubber stamp approval, I didn't pull down and test this, but I know previously the updates I had tried and rolled back had broken stuff, and I guess this has happened again

Awesome, I can't hit merge. :) Looks like perms were changed, so only folks flagged in the repo can ever.

**Comment by nschonni** [comment]
Looks like there are some build failures https://github.com/canada-ca/aia-eia-js/actions/runs/4246561469/jobs/7383529599

**Pull request merged**
