### PR TITLE
Customize wet cdts footer and breadcrumbs for Open Canada.

### PR DESCRIPTION
**Pull request by thriuin**
Added the breadcrumbs and GCWeb footer used on Open Canada site

### CODE REVIEW

**Comment by gcharest** [comment]
Awesome, will review and merge shortly this PM!

Le sam. 25 mai 2019 11 h 31, Ross Thompson <notifications@github.com> a
écrit :

**Comment by thriuin** [comment]
Great, thanks! Because this is an application, I'm  not sure it needs or should even have the full menu. Maybe this is enough.

**Comment by gcharest** [comment]
We'll see, it really just needs to fit within your standards.

I had to fix the JSON, will test tonight.

Le sam. 25 mai 2019 13 h 10, Ross Thompson <notifications@github.com> a
écrit :

**Comment by thriuin** [comment]
Let's discuss Monday - have a great weekend!

**Pull request merged**
